language: node_js
notifications:
  email: false
before_install: npm config set progress=false && npm i -g npm@latest --no-audit
install: npm ci --no-audit
jobs:
  include:
  - node_js: lts/*
    script:
    - npm test
    env: Runs the tests on node.js LTS.
  - node_js: node
    script:
    - npm test
    env: Runs the tests on node.js Stable.
